apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb-to-nginx-ingress
  namespace: ingress-nginx
  annotations:
    # Set the load balancer type and target mode
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # NGINX health check endpoint on port 10254
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/healthcheck-port: "10254"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingress-nginx-controller
                port:
                  number: 80