plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running

keyed_groups:
  - key: tags.Name
    prefix: k8s
    separator: "_"

hostnames:
   - 'private-ip-address'

compose:
  node_priv_ip: private_ip_address

groups:
  k8s_cluster: "'control_plane' in tags.Name or 'data_plane' in tags.Name"


