- name: join dataplane node 
  command: "{{ join_command_raw.stdout }}"
  args:
    # Makes the task idempotent so it doesn't fail if the node has already joined
    creates: /etc/kubernetes/kubelet.conf
  delegate_to: "{{ groups['k8s_data_plane'] }}"
